### ISSUE TITLE
Including multiple random effects in an mblogit model

### ISSUE THREAD

**Issue by asutto** [melff/mclogit#11]
Hello,

I am wondering if it is possible to fit multiple un-nested random effects within an mblogit model. I am able to run the model with either random effect and can nest them as well, but in this case it does not make sense to nest the random effects and would be best to treat them separately. For example, in lmer I know the syntax would be y ~ x + (1|random effect 1) + (1|random effect 2), but is it possible to do something similar to this in an mblogit model? Happy to provide additional information and code but thought it would be best to ask this question at a conceptual level first before delving into specifics.

Thank you!

**Comment by melff** [comment]
Since release 0.9 it is possible to fit non-nested random effects. At present, it is possible to specify such non-nested random effects by passing a list of formulae as a `random=` argument to `mclogit()` or `mblogit()`. Unfortunately, I have not yet found the time to upload release 0.9 to CRAN, but I intend to do that in the next few weeks.
